"""阿里云流式语音合成（FlowingSpeechSynthesizer）中文音色目录。

仅收录「支持语言包含中文」的音色：普通话 / 多情感 / 童声 / 各地方言（粤语、
台湾话、四川话、东北话、天津话、湖南话、浙普等）；排除纯英文/日/韩/俄/西/意/
法/德/泰/印尼/马来/菲律宾/越南等外语音色，以及 *_ecmix 英中混合英文音色。
来源：阿里云智能语音交互「音色列表」文档。前端语音浮层「音色」下拉据此渲染，
首项另加「本地」（浏览器 speechSynthesis）。每项 value 为 StartSynthesis 的
payload.voice 取值，label 为「中文名·类型」展示。
"""

ALIYUN_TTS_VOICES = [
    {"value": "abin", "label": "阿斌·广东普通话"},
    {"value": "zhixiaobai", "label": "知小白·普通话女声"},
    {"value": "zhixiaoxia", "label": "知小夏·普通话女声"},
    {"value": "zhixiaomei", "label": "知小妹·普通话女声"},
    {"value": "zhigui", "label": "知柜·普通话女声"},
    {"value": "zhishuo", "label": "知硕·普通话男声"},
    {"value": "aixia", "label": "艾夏·普通话女声"},
    {"value": "zhifeng_emo", "label": "知锋·多情感男声"},
    {"value": "zhibing_emo", "label": "知冰·多情感男声"},
    {"value": "zhimiao_emo", "label": "知妙·多情感女声"},
    {"value": "zhimi_emo", "label": "知米·多情感女声"},
    {"value": "zhiyan_emo", "label": "知燕·多情感女声"},
    {"value": "zhibei_emo", "label": "知贝·多情感童声"},
    {"value": "zhitian_emo", "label": "知甜·多情感女声"},
    {"value": "xiaoyun", "label": "小云·标准女声"},
    {"value": "xiaogang", "label": "小刚·标准男声"},
    {"value": "ruoxi", "label": "若兮·温柔女声"},
    {"value": "siqi", "label": "思琪·温柔女声"},
    {"value": "sijia", "label": "思佳·标准女声"},
    {"value": "sicheng", "label": "思诚·标准男声"},
    {"value": "aiqi", "label": "艾琪·温柔女声"},
    {"value": "aijia", "label": "艾佳·标准女声"},
    {"value": "aicheng", "label": "艾诚·标准男声"},
    {"value": "aida", "label": "艾达·标准男声"},
    {"value": "ninger", "label": "宁儿·标准女声"},
    {"value": "ruilin", "label": "瑞琳·标准女声"},
    {"value": "siyue", "label": "思悦·温柔女声"},
    {"value": "aiya", "label": "艾雅·严厉女声"},
    {"value": "aimei", "label": "艾美·甜美女声"},
    {"value": "aiyu", "label": "艾雨·自然女声"},
    {"value": "aiyue", "label": "艾悦·温柔女声"},
    {"value": "aijing", "label": "艾婧·严厉女声"},
    {"value": "xiaomei", "label": "小美·甜美女声"},
    {"value": "aina", "label": "艾娜·浙普女声"},
    {"value": "yina", "label": "伊娜·浙普女声"},
    {"value": "sijing", "label": "思婧·严厉女声"},
    {"value": "sitong", "label": "思彤·儿童音"},
    {"value": "xiaobei", "label": "小北·萝莉女声"},
    {"value": "aitong", "label": "艾彤·儿童音"},
    {"value": "aiwei", "label": "艾薇·萝莉女声"},
    {"value": "aibao", "label": "艾宝·萝莉女声"},
    {"value": "shanshan", "label": "姗姗·粤语女声"},
    {"value": "aiyuan", "label": "艾媛·知心姐姐"},
    {"value": "aiying", "label": "艾颖·软萌童声"},
    {"value": "aixiang", "label": "艾祥·磁性男声"},
    {"value": "aimo", "label": "艾墨·情感男声"},
    {"value": "aiye", "label": "艾晔·青年男声"},
    {"value": "aiting", "label": "艾婷·电台女声"},
    {"value": "aifan", "label": "艾凡·情感女声"},
    {"value": "chuangirl", "label": "小玥·四川话女声"},
    {"value": "aishuo", "label": "艾硕·自然男声"},
    {"value": "qingqing", "label": "青青·台湾话女声"},
    {"value": "cuijie", "label": "翠姐·东北话女声"},
    {"value": "xiaoze", "label": "小泽·湖南男声"},
    {"value": "ainan", "label": "艾楠·广告男声"},
    {"value": "aihao", "label": "艾浩·资讯男声"},
    {"value": "aiming", "label": "艾茗·诙谐男声"},
    {"value": "aixiao", "label": "艾笑·资讯女声"},
    {"value": "aichu", "label": "艾厨·舌尖男声"},
    {"value": "aiqian", "label": "艾倩·资讯女声"},
    {"value": "aishu", "label": "艾树·资讯男声"},
    {"value": "airu", "label": "艾茹·新闻女声"},
    {"value": "jiajia", "label": "佳佳·粤语女声"},
    {"value": "taozi", "label": "桃子·粤语女声"},
    {"value": "guijie", "label": "柜姐·亲切女声"},
    {"value": "stella", "label": "Stella·知性女声"},
    {"value": "stanley", "label": "Stanley·沉稳男声"},
    {"value": "kenny", "label": "Kenny·沉稳男声"},
    {"value": "rosa", "label": "Rosa·自然女声"},
    {"value": "mashu", "label": "马树·儿童剧男声"},
    {"value": "zhiqi", "label": "知琪·温柔女声"},
    {"value": "zhichu", "label": "知厨·舌尖男声"},
    {"value": "xiaoxian", "label": "小仙·亲切女声"},
    {"value": "yuer", "label": "悦儿·儿童剧女声"},
    {"value": "maoxiaomei", "label": "猫小美·活力女声"},
    {"value": "zhixiang", "label": "知祥·磁性男声"},
    {"value": "zhijia", "label": "知佳·标准女声"},
    {"value": "zhinan", "label": "知楠·广告男声"},
    {"value": "zhiqian", "label": "知倩·资讯女声"},
    {"value": "zhiru", "label": "知茹·新闻女声"},
    {"value": "zhide", "label": "知德·新闻男声"},
    {"value": "zhifei", "label": "知飞·激昂解说"},
    {"value": "aifei", "label": "艾飞·激昂解说"},
    {"value": "yaqun", "label": "亚群·卖场广播"},
    {"value": "qiaowei", "label": "巧薇·卖场广播"},
    {"value": "dahu", "label": "大虎·东北话男声"},
    {"value": "zhilun", "label": "知伦·悬疑解说"},
    {"value": "ailun", "label": "艾伦·悬疑解说"},
    {"value": "jielidou", "label": "杰力豆·治愈童声"},
    {"value": "zhiwei", "label": "知薇·萝莉女声"},
    {"value": "laotie", "label": "老铁·东北老铁"},
    {"value": "laomei", "label": "老妹·吆喝女声"},
    {"value": "aikan", "label": "艾侃·天津话男声"},
    {"value": "zhitian", "label": "知甜·甜美女声"},
    {"value": "zhiqing", "label": "知青·台湾话女声"},
    {"value": "zhimao", "label": "知猫·普通话女声"},
    {"value": "zhiyuan", "label": "知媛·普通话女声"},
    {"value": "zhiya", "label": "知雅·普通话女声"},
    {"value": "zhiyue", "label": "知悦·普通话女声"},
    {"value": "zhida", "label": "知达·普通话男声"},
    {"value": "zhistella", "label": "知莎·普通话女声"},
    {"value": "kelly", "label": "Kelly·香港粤语女声"},
]


ALIYUN_EMOTION_VOICE_CATEGORIES = {
    "zhifeng_emo": ["angry", "fear", "happy", "neutral", "sad", "surprise"],
    "zhibing_emo": ["angry", "fear", "happy", "neutral", "sad", "surprise"],
    "zhimiao_emo": [
        "serious",
        "sad",
        "disgust",
        "jealousy",
        "embarrassed",
        "happy",
        "fear",
        "surprise",
        "neutral",
        "frustrated",
        "affectionate",
        "gentle",
        "angry",
        "newscast",
        "customer-service",
        "story",
        "living",
    ],
    "zhimi_emo": ["angry", "fear", "happy", "hate", "neutral", "sad", "surprise"],
    "zhiyan_emo": ["neutral", "happy", "angry", "sad", "fear", "hate", "surprise", "arousal"],
    "zhibei_emo": ["neutral", "happy", "angry", "sad", "fear", "hate", "surprise"],
    "zhitian_emo": ["neutral", "happy", "angry", "sad", "fear", "hate", "surprise"],
}


def is_emotion_voice(voice_id: str | None) -> bool:
    return bool(voice_id and voice_id in ALIYUN_EMOTION_VOICE_CATEGORIES)


def emotion_categories_for_voice(voice_id: str | None) -> list[str]:
    if not voice_id:
        return []
    return list(ALIYUN_EMOTION_VOICE_CATEGORIES.get(voice_id, []))
